#! /bin/sh

# Download Chrome
wget -O /tmp/chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

# Install Chrome
dpkg -i /tmp/chrome.deb

# Install the dependencies
apt -f -y install

# Remove the package
rm -rf /tmp/chrome.deb
