#! /bin/sh

# Remove unwanted applications
apt purge --autoremove gnome-games gnome-contacts gnome-documents gnome-photos \
transmission-common gnome-weather gnome-orca gnome-online-accounts gnome-online-miners \
gnome-calendar gnome-maps gnome-music gnome-sushi polari evolution gnome-dictionary \
cheese rhythmbox totem gnome-getting-started-docs gnome-sound-recorder simple-scan \
gnome-clocks reportbug seahorse gnome-software synaptic gnome-disk-utility gnome-logs \
gnome-characters gnome-color-manager gnome-font-viewer gnome-user-guide gnome-accessibility-themes \
gnome-orca gnome-online-accounts baobab tracker avahi-daemon yelp file-roller \
shotwell brasero libreoffice-common inkscape gimp gnome-calculator vinagre
