#! /bin/sh

# Halt on error
set -e

# Restore default theme
update-alternatives --auto desktop-background
update-alternatives --auto desktop-background.xml
update-alternatives --auto desktop-grub
update-alternatives --auto desktop-lockscreen.xml
update-alternatives --auto desktop-login-background
update-alternatives --auto desktop-theme

# Apply GRUB background update into /boot
update-grub
update-initramfs -u

# Update dconf
dconf update
