#! /bin/sh

# Halt on error
set -e

# Setup Joy theme
update-alternatives --set desktop-background /usr/share/desktop-base/joy-theme/wallpaper/contents/images/1920x1200.svg
update-alternatives --set desktop-background.xml /usr/share/desktop-base/joy-theme/wallpaper/gnome-background.xml
update-alternatives --set desktop-grub /usr/share/desktop-base/joy-theme/grub/grub-16x9.png
update-alternatives --set desktop-lockscreen.xml /usr/share/desktop-base/joy-theme/lockscreen/gnome-background.xml
update-alternatives --set desktop-login-background /usr/share/desktop-base/joy-theme/login/background.svg
update-alternatives --set desktop-theme /usr/share/desktop-base/joy-theme

# Reconfigure Gnome
#dpkg-reconfigure desktop-base
echo "Execute : dpkg-reconfigure desktop-base"

# Setup Gnome Shell
glib-compile-schemas /usr/share/glib-2.0/schemas
